### ISSUE TITLE
Respect concurrency setting in all commands

### ISSUE THREAD

**Issue by tobami** [tobami/littlechef#235]
The `plugin` and `chef_deploy` cannot be executed in parallel.

Reported by Chengkai Liang on littlechef@googlegroups.com

**Comment by wilddog64** [comment]
The fix sub-commands that accepts concurrency (-c) are not consistent.  For exmaple, fix -c 5 node:all deploy_chef:method=omnibus,version=11.6 will fail.

Also, if nodes_with_tag are used, then -c 5 will take in effect.  But the roles assigned to nodes will not unless role: is given.

**Comment by tobami** [comment]
`nodes_with_tag` did apply the roles for me. Can you recheck with current master, which has the fix for `node:all`?

**Comment by wilddog64** [comment]
You mean pull from the master and install littlechef from there?

**Comment by wilddog64** [comment]
I checkout your latest version, and node:all works with concurrency chef
deployment, which is awesome ...  But nodes_with_tag still does not apply
the role I assign to the node if role: is not explicitly supply.  On second
thought, maybe this is a good thing, cause what if sometimes I just want to
execute the plugin but don't bother with role ...

-Chengkai

**Comment by tobami** [comment]
But if you just want to execute the plugin you will be running "fix
nodes_with_tag:MYTAG plugin:MYPLUGIN", so of course no roles are applied,
just the plugin. If you want a *configuration run*, then you type "fix
nodes_with_tag:MYTAG"

2015-01-27 16:21 GMT+01:00 chengkai <notifications@github.com>:

**Comment by wilddog64** [comment]
That's cool.  Thanks.
