### ISSUE TITLE
method for deploying littlechef plugins

### ISSUE THREAD

**Issue by wilddog64** [tobami/littlechef#248]
Littlechef's plugin is great but there no central location for storing these plugins.  The current plugin samples come with distribution is not even install or aware.  The plugin command always looking plugins directory in a current project/directory.  To better share the code, it is better that the plugins directory can be install at a share location and provide users a way to deploy the custom plugins.

**Comment by tobami** [comment]
The idea is that you save your plugins in your *kitchen* directory, and check it in version control like all the cookbooks.

Does that make sense for you?

**Comment by wilddog64** [comment]
But that prevent me from sharing plugins for multiple projects ...  If I
have couples projects that need the same plugins, then I have to duplicate
them in every single project.  Or maybe I can just create a repo for those
plugins and use git submodule to manage them.

-Chengkai

**Comment by tobami** [comment]
But that is the same problem you have if you want to reuse one of your cookbooks in several projects isn't it?

**Comment by wilddog64** [comment]
That I can use berkshelf to manage those thing, and I don't have dup those
cookbook into each project.  As for littlechef plugin, there no tool to
manage that except you save them in one spot.  If I follow Berkshelf way to
use environment application cookbook pattern, then those plugins will be
duplicated for each environment application cookbook.

-Chengkai

**Comment by wilddog64** [comment]
The other thought is to allow plugins to live on its own repo.  This way, we can easily manage them use git submodule or git subtree.  It also allow we as users to contribute our custom plugins back to community for greater sharing.

**Comment by tobami** [comment]
That sounds like a great idea!

**Comment by wilddog64** [comment]
what's your timeline to implement this?

**Comment by tobami** [comment]
@wilddog64 I have created a new repo for plugins, as you suggested:
https://github.com/tobami/littlechef-plugins

Feel free to send pull requests for changes or additions!
